INSERT INTO FBI_ACTIVE_SHOOTERS.RawRecords
(DataSourceId,IncidentName,Date,Time,State,Location,ShooterName,ShooterGender,ShooterAge,Rifles,Shotguns,Handguns,Deaths,Wounded,`Total(Calculated)`,TerminatingEvent,ShooterFate,SurrenderedDuringIncident)
VALUES
('2020', '9ine Ultra Lounge', '19-Jan-20', '11:30 PM', 'Missouri', 'Commerce', 'Jahron Swift', 'MALE', '29', '0', '0', '2', '1', '16', '17', 'Shot by security guard (Killed)', 'Killed', 'NO'),
('2020', 'NYPD 41st Precinct Office', '8-Feb-20', '8:30 PM', 'New York', 'Government', 'Robert Williams', 'MALE', '45', '0', '0', '1', '0', '2', '2', 'Fled the scene; Surrendered', 'Escaped (Arrested Later)', 'YES'),
('2020', 'Portstewart Senior Apartments ', '20-Feb-20', '4:18 PM', 'Idaho', 'Residence', 'Roger Nordberg', 'MALE', '87', '0', '0', '1', '1', '3', '4', 'Suicide after engaging police', 'Suicide', 'NO'),
('2020', 'Molson Coors Building', '26-Feb-20', '2:08 PM', 'Wisconsin', 'Commerce', 'Anthony Ferrill', 'MALE', '51', '0', '0', '2', '5', '0', '5', 'Suicide before police arrived', 'Suicide', 'NO'),
('2020', 'Kum & Go Gas Station', '15-Mar-20', '11:24 PM', 'Missouri', 'Commerce', 'Joaquin Roman', 'MALE', '31', '1', '0', '1', '4', '2', '6', 'Suicide after engaging police', 'Suicide', 'NO'),
('2020', 'Unspecified Shopping Center in Tulsa, Oklahoma', '27-Mar-20', '6:20 PM', 'Oklahoma', 'Commerce', 'Ashley Porter', 'FEMALE', '34', '0', '0', '1', '0', '0', '0', 'Shot by security guard (Killed)', 'Killed', 'NO'),
('2020', 'McDonald''s Restaurant', '6-May-20', '6:20 PM', 'Oklahoma', 'Commerce', 'Gloria Woody', 'FEMALE', '32', '0', '0', '1', '0', '4', '4', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Super 8 Hotel', '17-May-20', '12:38 AM', 'Illinois', 'Commerce', 'Antonio Wilson', 'MALE', '35', '0', '0', '2', '1', '2', '3', 'Suicide after engaging police', 'Suicide', 'NO'),
('2020', 'Westgate Entertainment District', '20-May-20', '7:25 PM', 'Arizona', 'Commerce', 'Armando Hernandez', 'MALE', '20', '1', '0', '0', '0', '3', '3', 'Surrendered to Police', 'Arrested', 'YES'),
('2020', 'Naval Air Station Corpus Christi', '21-May-20', '6:00 AM', 'Texas', 'Government', 'Adam Alsahli', 'MALE', '20', '1', '1', '1', '0', '1', '1', 'Shot by police (Killed)', 'Killed', 'NO'),
('2020', 'Centennial Bridge', '27-May-20', '11:00 AM', 'Kansas', 'Open Space', 'Jason Westrem', 'MALE', '37', '1', '0', '1', '0', '1', '1', 'Off-Duty soldier intervention with automobile', 'Arrested', 'NO'),
('2020', 'Indoor Comfort and Heating', '1-Jun-20', '8:56 AM', 'Tennessee', 'Commerce', 'Bobby Mercer', 'MALE', '48', '0', '0', '1', '2', '0', '2', 'Suicide after engaging police', 'Suicide', 'NO'),
('2020', 'Multiple Locations in Paso Robles, California', '10-Jun-20', '3:45 AM', 'California', 'Open Space', 'Mason Lira', 'MALE', '26', '0', '0', '3', '1', '4', '5', 'Fled the scene; Shot by police (Killed)', 'Killed', 'NO'),
('2020', 'Rebar Bar and Lounge', '12-Jun-20', '11:30 PM', 'Texas', 'Commerce', 'Jenelius Crew', 'MALE', '37', '1', '0', '0', '0', '8', '8', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Giuseppe''s Pizzeria', '19-Jun-20', '11:45 AM', 'Florida', 'Commerce', 'William Carrodus', 'MALE', '56', '1', '0', '0', '1', '0', '1', 'Shooter completed goal and stopped', 'Arrested', 'YES'),
('2020', 'Applebee''s Restaurant', '22-Jun-20', '9:30 PM', 'Missouri', 'Commerce', 'Courtney Demond Washington', 'MALE', '28', '0', '0', '1', '1', '2', '3', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Bunn-O-Matic Warehouse', '26-Jun-20', '11:03 AM', 'Illinois', 'Commerce', 'Michael L. Collins', 'MALE', '48', '0', '0', '2', '3', '0', '3', 'Fled the scene', 'Escaped (Suicide Later)', 'NO'),
('2020', 'Walmart Distribution Facility', '27-Jun-20', '3:30 PM', 'California', 'Commerce', 'Louis Lane', 'MALE', '31', '1', '0', '0', '2', '4', '6', 'Shot by police (Killed)', 'Killed', 'NO'),
('2020', 'Jefferson Square Park', '27-Jun-20', '8:59 PM', 'Kentucky', 'Open Space', 'Steven Nelson Lopez', 'MALE', '23', '0', '0', '1', '1', '0', '1', null, 'Arrested', null),
('2020', 'Unspecified Residential Address in Manteca, California', '25-Jul-20', '12:00 AM', 'California', 'Residence', null, 'MALE', null, '0', '0', '1', '0', '9', '9', 'Fled the scene', 'Escaped (Never Caught)', 'NO'),
('2020', 'Residential Neighborhood in Eagle River, Alaska', '30-Jul-20', '6:20 AM', 'Alaska', 'Open Space', 'Todd Driskill', 'MALE', '57', '1', '0', '0', '0', '1', '1', 'Shot by police (Survived)', 'Arrested', 'NO'),
('2020', 'Multiple Locations in Tampa, Florida', '30-Jul-20', '6:52 PM', 'Florida', 'Open Space', 'Antonio Cruz Ortiz', 'MALE', '31', '1', '0', '0', '0', '5', '5', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Tin Cup Campground', '1-Aug-20', '10:15 PM', 'Idaho', 'Open Space', 'Russell Liddell', 'MALE', '73', '0', '0', '1', '0', '0', '0', 'Shot by off-duty police (Killed)', 'Killed', 'NO'),
('2020', 'Multiple Locations in Dayton, Texas', '17-Aug-20', '11:15 AM', 'Texas', 'Residence', 'Michael Wettstein', 'MALE', '60', '1', '1', '0', '3', '2', '5', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Vons Gas Station', '21-Aug-20', '11:15 AM', 'California', 'Commerce', 'Scott Cameron Huffman', 'MALE', '42', '0', '0', '1', '0', '0', '0', 'Shot by police (Killed)', 'Killed', 'NO'),
('2020', 'Interstate 95 in Nashville, North Carolina', '5-Sep-20', '6:45 PM', 'North Carolina', 'Open Space', 'Franklin Joseph Dangerfield', 'MALE', '33', '0', '1', '0', '0', '3', '3', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', '"Next Generation All Gas" Protest/Block Party', '5-Sep-20', '3:00 AM', 'Florida', 'Open Space', null, null, null, null, null, null, '0', '6', '6', 'Fled the scene', 'Escaped (Never Caught)', 'NO'),
('2020', 'East Market & Restaurant', '3-Oct-20', '3:10 PM', 'California', 'Commerce', 'Hassibullah Shams Hassib', 'MALE', '33', '0', '0', '1', '2', '1', '3', 'Suicide before police arrived', 'Suicide', 'NO'),
('2020', 'Infinity Lounge', '10-Oct-20', '2:00 AM', 'South Carolina', 'Commerce', 'Adrian McCrea', 'MALE', '34', '1', '0', '0', '0', '8', '8', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Sahara Theater', '31-Oct-20', '1:35 AM', 'California', 'Commerce', 'Edgar Nava-Ayala', 'MALE', '34', '1', '0', '0', '0', '5', '5', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Sports Unlimited Bar and Lounge', '7-Nov-20', '12:10 AM', 'South Carolina', 'Commerce', 'Shawn David Durham', 'MALE', '34', '0', '0', '1', '1', '3', '4', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Mayfair Mall', '20-Nov-20', '2:50 PM', 'Wisconsin', 'Commerce', 'Xavier Sevilla', 'MALE', '15', '0', '0', '1', '0', '8', '8', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'Sonic Restaurant', '21-Nov-20', '9:23 PM', 'Nebraska', 'Commerce', 'Roberto Carlos Silva Jr.', 'MALE', '23', '0', '1', '2', '2', '2', '4', 'Surrendered to Police', 'Arrested', 'YES'),
('2020', 'Multiple Locations in Henderson, Nevada, and Parker, Arizona', '26-Nov-20', '12:54 AM', 'Nevada & Arizona', 'Open Space', 'Kayleigh Lewis & Christopher McDonnell & Shawn McDonnell', 'FEMALE & MALE & MALE', '25 & 28 & 30', '0', '0', '3', '1', '4', '5', 'Fled the scene & Fled the scene & Fled the scene', 'Escaped (Arrested Later) & Escaped (Arrested Later) & Escaped (Arrested Later)', 'NO & NO & NO'),
('2020', 'West Garfield Park', '4-Dec-20', '10:50 PM', 'Illinois', 'Open Space', null, null, null, null, null, null, '0', '4', '4', 'Fled the scene', 'Escaped (Never Caught)', 'NO'),
('2020', 'La Vaquita Deli', '12-Dec-20', '6:10 PM', 'New York', 'Commerce', 'Dionicio Calderon', 'MALE', '62', '0', '0', '1', '2', '2', '4', 'Fled the scene', 'Escaped (Arrested Later)', 'NO'),
('2020', 'U.S. Army Recruiting Station', '14-Dec-20', '6:21 PM', 'North Carolina', 'Government', 'James Alexander Cooper', 'MALE', '36', '0', '0', '1', '0', '0', '0', 'Shooter completed goal and stopped', 'Arrested', 'NO'),
('2020', 'Get Glammed Beauty Bar', '19-Dec-20', '12:24 AM', 'Illinois', 'Commerce', null, null, null, null, null, null, '0', '5', '5', 'Fled the scene', 'Escaped (Never Caught)', 'NO'),
('2020', 'Don Carter Lanes', '26-Dec-20', '6:55 PM', 'Illinois', 'Commerce', 'Duke Webb', 'MALE', '37', '0', '0', '2', '3', '3', '6', 'Shooter completed goal and stopped', 'Arrested', 'NO'),
('2020', 'Epic Ultra Lounge', '31-Dec-20', '10:00 PM', 'Indiana', 'Commerce', null, null, null, null, null, null, '1', '3', '4', 'Fled the scene', 'Escaped (Never Caught)', 'NO');
