INSERT INTO FBI_ACTIVE_SHOOTERS_2000_2018.STATELOOKUP (NAME) VALUES ('Alabama'),('Alaska'),('Arizona'),('Arkansas'),('California'),('Colorado'),('Connecticut'),('Delaware'),('District of Columbia'),('Florida'),('Georgia'),('Hawaii'),('Idaho'),('Illinois'),('Indiana'),('Iowa'),('Kansas'),('Kentucky'),('Louisiana'),('Maine'),('Maryland'),('Massachusetts'),('Michigan'),('Minnesota'),('Mississippi'),('Missouri'),('Montana'),('Nebraska'),('Nevada'),('New Hampshire'),('New Jersey'),('New Mexico'),('New York'),('North Carolina'),('North Dakota'),('Ohio'),('Oklahoma'),('Oregon'),('Pennsylvania'),('Rhode Island'),('South Carolina'),('South Dakota'),('Tennessee'),('Texas'),('Utah'),('Vermont'),('Virginia'),('Washington'),('West Virginia'),('Wisconsin'),('Wyoming');

INSERT INTO FBI_ACTIVE_SHOOTERS_2000_2018.RawRecords
(IncidentName,Date,Time,State,Location,ShooterName,ShooterGender,ShooterAge,Rifles,Shotguns,Handguns,Deaths,Wounded,`Total(Calculated)`,TerminatingEvent,ShootersFate,SurrenderedDuringIncident)
VALUES
('Edgewater Technology, Inc.','26-Dec-00','11:15 AM','Massachusetts','Commerce','Michael M. McDermott','MALE','42','1','1','1','7','0','7','Shooter completed goal and stopped','Arrested','YES'),
('Amko Trading Store','9-Jan-01','12:00 PM','Texas','Commerce','Ki Yung Park','MALE','54','0','0','2','4','0','4','Suicide when police arrived','Suicide','NO'),
('Navistar International Corporation Factory','5-Feb-01','9:40 AM','Illinois','Commerce','William Daniel Baker','MALE','57','2','1','1','4','4','8','Suicide before police arrived','Suicide','NO'),
('Santana High School','5-Mar-01','9:20 AM','California','Education','Charles Andrew Williams Jr','MALE','15','0','0','1','2','13','15','Surrendered to Police','Arrested','YES'),
('Granite Hills High School','22-Mar-01','12:55 PM','California','Education','Jason Anthony Hoffman','MALE','18','0','1','1','0','5','5','Shot by police (Survived)','Arrested','NO'),
('Laidlaw Transit Services Maintenance Yard','23-Apr-01','6:00 AM','California','Commerce','Cathline Repunte','FEMALE','36','0','0','1','1','3','4','Physical intervention by civilian','Arrested','NO'),
('Nu-Wood Decorative Millwork Plant','6-Dec-01','2:31 PM','Indiana','Commerce','Robert L. Wissman','MALE','36','0','1','0','1','6','7','Suicide before police arrived','Suicide','NO'),
('Appalachian School of Law','16-Jan-02','1:15 PM','Virginia','Education','Peter Odighizuma','MALE','43','0','0','1','3','3','6','Physical intervention by civilian & off-duty police','Arrested','NO'),
('Bertrand Products, Inc.','22-Mar-02','8:15 AM','Indiana','Commerce','William Lockey','MALE','54','1','1','0','4','5','9','Suicide after engaging police','Suicide','NO'),
('Tom Bradley International Terminal at Los Angeles International Airport','4-Jul-02','11:30 AM','California','Government','Hesham Mohamed Ali Hadayet','MALE','43','0','0','2','2','2','4','Shot by security guard (Killed)','Killed','NO'),
('18 Miles of U.S. Route 64 from Sallisaw to Roland, Oklahoma','26-Oct-02','5:00 PM','Oklahoma','Open Space','Daniel Hawke Fears','MALE','18','0','1','0','2','8','10','Automobile crash into police blockade','Arrested','NO'),
('Labor Ready, Inc.','25-Feb-03','6:25 AM','Alabama','Commerce','Emanuel Burl Patterson','MALE','23','0','0','1','4','1','5','Fled the scene','Escaped (Arrested Later)','NO'),
('Red Lion Junior High School','24-Apr-03','7:34 AM','Pennsylvania','Education','James Sheets','MALE','14','0','0','3','1','0','1','Suicide before police arrived','Suicide','NO'),
('Case Western Reserve University, Weatherhead School of Management','9-May-03','3:55 PM','Ohio','Education','Biswanath A. Halder','MALE','62','1','0','1','1','2','3','Shot by police (Survived)','Arrested','NO'),
('Modine Manufacturing Company','1-Jul-03','10:28 PM','Missouri','Commerce','Jonathon W. Russell','MALE','25','0','0','1','3','5','8','Suicide after engaging police','Suicide','NO'),
('Lockheed Martin Subassembly Plant','8-Jul-03','9:30 AM','Mississippi','Commerce','Douglas Paul Williams','MALE','48','1','1','0','6','8','14','Suicide before police arrived','Suicide','NO'),
('Kanawha County Board of Education','17-Jul-03','7:00 PM','West Virginia','Education','Richard Dean Bright','MALE','58','2','0','2','0','1','1','Physical intervention by civilian','Arrested','NO'),
('Gold Leaf Nursery','28-Jul-03','11:40 AM','Florida','Commerce','Agustin Casarubias-Dominguez (aka Andres Casarrubias)','MALE','45','0','0','1','3','0','3','Physical intervention by civilian','Arrested','NO'),
('Andover Industries','19-Aug-03','8:20 AM','Ohio','Commerce','Richard Wayne Shadle','MALE','32','0','0','4','1','2','3','Suicide before police arrived','Suicide','NO'),
('Windy City Core Supply, Inc.','27-Aug-03','8:30 AM','Illinois','Commerce','Salvador Tapia Solis','MALE','36','0','0','1','6','0','6','Shot by police (Killed)','Killed','NO'),
('Rocori High School','24-Sep-03','11:35 AM','Minnesota','Education','John Jason McLaughlin','MALE','15','0','0','1','2','0','2','Verbal intervention by civilian','Arrested','YES'),
('Watkins Motor Lines','6-Nov-03','9:57 AM','Ohio','Commerce','Joseph John Eschenbrenner, III (aka Tom West)','MALE','50','0','0','2','2','3','5','Fled the scene','Escaped (Arrested Later)','NO'),
('Columbia High School','9-Feb-04','10:30 AM','New York','Education','Jon William Romano','MALE','16','0','1','0','0','1','1','Physical intervention by civilian','Arrested','NO'),
('ConAgra Plant','2-Jul-04','5:00 PM','Kansas','Commerce','Elijah J. Brown','MALE','21','0','0','1','6','2','8','Suicide before police arrived','Suicide','NO'),
('Radio Shack in Gateway Mall','18-Nov-04','6:45 PM','Florida','Commerce','Justin Michael Cudar','MALE','25','0','0','1','2','1','3','Suicide before police arrived','Suicide','NO'),
('Private Property near Meteor, Wisconsin','21-Nov-04','12:00 PM','Wisconsin','Open Space','Chai Soua Vang','MALE','36','1','0','0','6','2','8','Fled the scene','Arrested','NO'),
('DaimlerChrysler’s Toledo North Assembly Plant','26-Jan-05','8:34 PM','Ohio','Commerce','Myles Wesley Meyers','MALE','54','0','1','0','1','2','3','Suicide before police arrived','Suicide','NO'),
('Best Buy in Hudson Valley Mall','13-Feb-05','3:15 PM','New York','Commerce','Robert Charles Bonelli Jr.','MALE','25','1','0','0','0','2','2','Physical Intervention by Civilian','Arrested','NO'),
('Living Church of God','12-Mar-05','12:51 PM','Wisconsin','House of Worship','Terry M. Ratzmann','MALE','44','0','0','1','7','4','11','Suicide before police arrived','Suicide','NO'),
('Red Lake High School and Residence','21-Mar-05','2:49 PM','Minnesota','Education','Jeffery James Weise','MALE','16','0','1','2','9','6','15','Suicide after engaging police','Suicide','NO'),
('California Auto Specialist and Apartment Complex','8-Aug-05','2:40 PM','California','Commerce','Louis Mitchell Jr.','MALE','35','0','0','1','3','3','6','Shot by police (Survived); fled the scene','Escaped (Arrested Later)','NO'),
('Parking Lots in Philadelphia, Pennsylvania','7-Oct-05','10:13 AM','Pennsylvania','Open Space','Alexander Elkin','MALE','45','0','0','1','2','0','2','Suicide after engaging police','Suicide','NO'),
('Campbell County Comprehensive High School','8-Nov-05','2:14 PM','Tennessee','Education','Kenneth S. Bartley','MALE','14','0','0','1','1','2','3','Physical intervention by civilian','Arrested','NO'),
('Tacoma Mall','20-Nov-05','12:00 PM','Washington','Commerce','Dominick Sergil Maldonado','MALE','20','1','0','1','0','6','6','Verbal intervention by civilian','Arrested','YES'),
('Burger King and Huddle House','22-Nov-05','6:10 AM','South Carolina','Commerce',null,'MALE',null,'1','0','0','1','2','3','Fled the scene','Escaped (Never Caught)','NO'),
('Santa Barbara U.S. Postal Processing and Distribution Center','30-Jan-06','7:15 PM','California','Government','Jennifer San Marco','FEMALE','44','0','0','1','6','0','6','Suicide before police arrived','Suicide','NO'),
('Pine Middle School','14-Mar-06','9:00 AM','Nevada','Education','James Scott Newman','MALE','14','0','0','1','0','2','2','Physical intervention by civilian','Arrested','NO'),
('Residence in Capitol Hill Neighborhood, Seattle, Washington','25-Mar-06','7:03 AM','Washington','Residence','Kyle Aaron Huff','MALE','28','1','1','1','6','2','8','Suicide when police arrived','Suicide','NO'),
('Safeway Warehouse','25-Jun-06','3:03 PM','Colorado','Commerce','Michael Julius Ford','MALE','22','0','0','1','1','5','6','Shot by police (Killed)','Killed','NO'),
('Jewish Federation of Greater Seattle','28-Jul-06','4:00 PM','Washington','House of Worship','Naveed Afzal Haq','MALE','30','0','0','2','1','5','6','Surrendered to Police','Arrested','YES'),
('Essex Elementary School and Two Residences','24-Aug-06','1:55 PM','Vermont','Education','Christopher Williams','MALE','26','0','0','1','2','2','4','Attempted Suicide (Survived)','Arrested','NO'),
('Orange High School and Residence','30-Aug-06','1:00 PM','North Carolina','Education','Alvaro Castillo','MALE','19','2','1','0','1','2','3','Physical intervention by police','Arrested','NO'),
('Weston High School','29-Sep-06','8:00 AM','Wisconsin','Education','Eric Jordan Hainstock','MALE','15','1','0','1','1','0','1','Physical intervention by civilian','Arrested','NO'),
('West Nickel Mines School','2-Oct-06','10:30 AM','Pennsylvania','Education','Charles Carl Roberts','MALE','32','1','1','1','5','5','10','Suicide when police arrived','Suicide','NO'),
('Memorial Middle School','9-Oct-06','7:40 AM','Missouri','Education','Thomas White','MALE','13','1','0','1','0','0','0','Verbal intervention by civilian','Arrested','YES'),
('Trolley Square Mall','12-Feb-07','6:45 PM','Utah','Commerce','Sulejman Talovic','MALE','18','0','1','1','5','4','9','Shot by police (Killed)','Killed','NO'),
('ZigZag Net, Inc.','12-Feb-07','8:00 PM','Pennsylvania','Commerce','Vincent Dortch','MALE','44','1','0','1','3','1','4','Suicide after engaging police','Suicide','NO'),
('Kenyon Press','5-Mar-07','9:00 AM','California','Commerce','Alonso Jose Mendez','MALE','68','0','0','1','0','3','3','Suicide before police arrived','Suicide','NO'),
('Virginia Polytechnic Institute and State University','16-Apr-07','7:15 AM','Virginia','Education','Seung Hui Cho','MALE','23','0','0','2','32','17','49','Suicide when police arrived','Suicide','NO'),
('Target Store','29-Apr-07','3:25 PM','Missouri','Commerce','David Wayne Logsdon','MALE','51','1','0','0','2','8','10','Shot by police (Killed)','Killed','NO'),
('Residence, Latah County Courthouse, and First Presbyterian Church','19-May-07','11:00 PM','Idaho','Government','Jason Kenneth Hamilton','MALE','36','2','0','0','3','3','6','Suicide when police arrived','Suicide','NO'),
('Liberty Transportation','8-Aug-07','3:15 PM','Ohio','Commerce','Calvin Coolidge Neyland Jr.','MALE','43','2','0','2','2','0','2','Fled the scene','Escaped (Arrested Later)','NO'),
('Co-op City Apartment Building’s Leasing Office','30-Aug-07','7:50 AM','New York','Commerce','Paulino Valenzuela','MALE','44','0','0','1','1','2','3','Fled the scene','Escaped (Arrested Later)','NO'),
('Giordano and Giordano Law Office','4-Oct-07','2:00 PM','Louisiana','Commerce','John Chester Ashley','MALE','63','0','0','1','2','3','5','Shot by police (Killed)','Killed','NO'),
('Residence in Crandon, Wisconsin','7-Oct-07','2:45 AM','Wisconsin','Residence','Tyler Peterson','MALE','20','1','0','0','6','1','7','Suicide after engaging police','Suicide','NO'),
('Am-Pac Tire Pros','8-Oct-07','7:30 AM','California','Commerce','Robert Becerra','MALE','29','0','0','1','1','2','3','Suicide before police arrived','Suicide','NO'),
('SuccessTech Academy','10-Oct-07','1:02 PM','Ohio','Education','Asa Halley Coon','MALE','14','0','0','2','0','4','4','Suicide before police arrived','Suicide','NO'),
('Von Maur in Westroads Mall','5-Dec-07','1:42 PM','Nebraska','Commerce','Robert Arthur Hawkins','MALE','19','1','0','0','8','4','12','Suicide before police arrived','Suicide','NO'),
('Youth with a Mission Training Center/New Life Church','9-Dec-07','12:29 AM','Colorado','House of Worship','Matthew John Murray','MALE','24','1','0','2','4','5','9','Shot by security guard, then committed suicided','Suicide','NO'),
('Kirkwood City Hall','7-Feb-08','7:00 PM','Missouri','Government','Charles Lee Thornton','MALE','52','0','0','2','6','0','6','Shot by police (Killed)','Killed','NO'),
('Louisiana Technical College','8-Feb-08','8:35 AM','Louisiana','Education','Latina Williams','FEMALE','23','0','0','1','2','0','2','Suicide before police arrived','Suicide','NO'),
('Cole Hall Auditorium, Northern Illinois University','14-Feb-08','3:00 PM','Illinois','Education','Steven Phillip Kazmierczak','MALE','27','0','1','3','5','16','21','Suicide before police arrived','Suicide','NO'),
('Wendy’s Fast Food Restaurant','3-Mar-08','12:15 PM','Florida','Commerce','Alburn Edward Blake','MALE','60','0','0','1','1','4','5','Suicide before police arrived','Suicide','NO'),
('Player’s Bar and Grill','25-May-08','2:25 AM','Nevada','Commerce','Ernesto Villagomez','MALE','30','0','0','1','2','2','4','Shot by civilian (Killed)','Killed','NO'),
('Atlantis Plastics Factory','25-Jun-08','12:00 AM','Kentucky','Commerce','Wesley Neal Higdon','MALE','25','0','0','1','5','1','6','Suicide before police arrived','Suicide','NO'),
('Tennessee Valley Unitarian Universalist Church','27-Jul-08','10:18 AM','Tennessee','House of Worship','Jim David Adkisson','MALE','58','0','1','0','2','7','9','Physical intervention by civilian','Arrested','NO'),
('Interstate 5 in Skagit County, Washington','2-Sep-08','2:15 PM','Washington','Open Space','Isaac Lee Zamora','MALE','28','1','0','0','6','4','10','Fled the scene','Escaped (Turned self in)','NO'),
('The Zone','24-Jan-09','10:37 PM','Oregon','Commerce','Erik Salvador Ayala','MALE','24','0','0','1','2','7','9','Attempted Suicide (Survived)','Arrested','NO'),
('Coffee and Geneva Counties, Alabama','10-Mar-09','4:00 PM','Alabama','Open Space','Michael Kenneth McLendon','MALE','28','1','0','0','10','1','11','Suicide after engaging police','Suicide','NO'),
('Pinelake Health and Rehabilitation Center','29-Mar-09','10:00 AM','North Carolina','Health Care','Robert Kenneth Stewart','MALE','45','1','1','1','8','3','11','Shot by police (Survived)','Arrested','NO'),
('American Civic Association Center','3-Apr-09','10:31 AM','New York','Commerce','Linh Phat Voong','MALE','41','0','0','2','13','4','17','Suicide before police arrived','Suicide','NO'),
('Kkottongnae Retreat Camp','7-Apr-09','7:23 PM','California','House of Worship','John Suchan Chong','MALE','69','0','0','1','1','2','3','Physical intervention by civilian','Arrested','NO'),
('Harkness Hall at Hampton University','26-Apr-09','12:57 AM','Virginia','Education','Odane Greg Maye','MALE','18','0','0','3','0','2','2','Attempted Suicide (Survived)','Arrested','NO'),
('Larose-Cut Off Middle School','18-May-09','9:00 AM','Louisiana','Education','Justin Doucet','MALE','15','0','0','1','0','0','0','Attempted Suicide (Survived)','Arrested','NO'),
('U.S. Army Recruiting Center','1-Jun-09','10:19 AM','Arkansas','Government','Carlos Leon Bledsoe','MALE','23','2','0','1','1','1','2','Fled the scene; Surrendered when caught','Arrested','NO'),
('United States Holocaust Memorial Museum','10-Jun-09','12:52 PM','District of Columbia','Government','James Wenneker von Brunn','MALE','88','1','0','0','1','0','1','Shot by police (Survived)','Arrested','NO'),
('Family Dental Care','1-Jul-09','10:30 AM','California','Commerce','Jaime Paredes','MALE','30','1','0','0','1','4','5','Surrendered to Police','Arrested','NO'),
('Club LT Tranz','25-Jul-09','4:40 AM','Texas','Commerce',null,null,null,null,null,null,'1','2','3','Fled the scene','Escaped (Never Caught)','NO'),
('LA Fitness','4-Aug-09','7:56 PM','Pennsylvania','Commerce','George Sodini','MALE','48','0','0','3','3','9','12','Suicide before police arrived','Suicide','NO'),
('Multiple Locations in Owosso, Michigan','11-Sep-09','7:20 AM','Michigan','Open Space','Harlan James Drake','MALE','33','0','0','3','2','0','2','Fled the scene','Escaped (Arrested Later)','NO'),
('Fort Hood Soldier Readiness Processing Center','5-Nov-09','1:20 PM','Texas','Government','Nidal Malik Hasan','MALE','39','0','0','2','13','32','45','Shot by police (Survived)','Arrested','NO'),
('Reynolds, Smith and Hills','6-Nov-09','11:44 AM','Florida','Commerce','Jason Samuel Rodriguez','MALE','40','0','0','1','1','5','6','Fled the scene','Escaped (Arrested Later)','NO'),
('Sandbar Sports Grill','7-Nov-09','7:28 PM','Colorado','Commerce','Richard Allan Moreau','MALE','63','0','0','1','1','3','4','Shooter completed goal and stopped','Arrested','YES'),
('Legacy Metrolab','10-Nov-09','11:49 AM','Oregon','Commerce','Robert Beiser','MALE','39','1','1','1','1','2','3','Suicide before police arrived','Suicide','NO'),
('Forza Coffee Shop','29-Nov-09','8:15 AM','Washington','Commerce','Maurice Clemmons','MALE','37','0','0','1','4','0','4','Shot by police (Killed)','Killed','NO'),
('Grady Crawford Construction Company','23-Dec-09','1:50 PM','Louisiana','Commerce','Richard Matthews','MALE','53','0','0','1','2','1','3','Physical intervention by civilian','Arrested','NO'),
('Lloyd D. George U.S. Courthouse and Federal Building','4-Jan-10','8:02 AM','Nevada','Government','Johnny Lee Wicks Jr','MALE','66','0','1','0','1','1','2','Shot by police (Killed)','Killed','NO'),
('ABB Plant','7-Jan-10','6:30 AM','Missouri','Commerce','Timothy Hendron','MALE','51','1','1','2','3','5','8','Suicide before police arrived','Suicide','NO'),
('Penske Truck Rental','12-Jan-10','2:00 PM','Georgia','Commerce','Jesse James Warren','MALE','60','0','0','2','3','2','5','Fled the scene','Escaped (Arrested Later)','NO'),
('Residence in Brooksville, Florida','14-Jan-10','2:59 PM','Florida','Residence','John William Kalisz','MALE','55','0','0','1','3','2','5','Shot by pollice (Survived)','Arrested','NO'),
('Farm King Store','3-Feb-10','12:45 PM','Illinois','Commerce','Jonathan Joseph Labbe','MALE','19','1','0','0','0','0','0','Suicide when police arrived','Suicide','NO'),
('Inskip Elementary School','10-Feb-10','12:49 PM','Tennessee','Education','Mark Stephen Foster','MALE','48','0','0','1','0','2','2','Fled the scene','Arrested','NO'),
('Shelby Center, University of Alabama','12-Feb-10','4:00 PM','Alabama','Education','Amy Bishop Anderson','FEMALE','44','0','0','1','3','3','6','Surrendered to Police','Arrested','NO'),
('Deer Creek Middle School','23-Feb-10','3:10 PM','Colorado','Education','Bruco Strongeagle Eastwood','MALE','32','1','0','0','0','2','2','Physical intervention by civilian','Arrested','NO'),
('The Pentagon','4-Mar-10','6:36 PM','Virginia','Government','John Patrick Bedell','MALE','36','0','0','1','0','2','2','Shot by police (Killed)','Killed','NO'),
('The Ohio State University, Maintenance Building','9-Mar-10','3:30 AM','Ohio','Education','Nathaniel Alvin Brown','MALE','50','0','0','2','1','1','2','Suicide before police arrived','Suicide','NO'),
('Publix Super Market','30-Mar-10','12:00 PM','Florida','Commerce','Arunya Rouch','FEMALE','41','0','0','1','1','0','1','Shot by police (Survived)','Arrested','NO'),
('Parkwest Medical Center','19-Apr-10','4:30 PM','Tennessee','Health Care','Abdo Ibssa','MALE','38','0','0','1','1','2','3','Suicide before police arrived','Suicide','NO'),
('Blue Sky Carnival','7-May-10','10:22 PM','New Jersey','Open Space','Rasheed Cherry','MALE','17','0','0','1','0','1','1','Shot by police (Survived)','Arrested','NO'),
('Boulder Stove and Flooring','17-May-10','11:05 AM','Colorado','Commerce','Robert Phillip Montgomery','MALE','53','0','0','1','2','0','2','Suicide before police arrived','Suicide','NO'),
('AT&T Cellular','27-May-10','1:00 PM','New York','Commerce','Abraham Dickan','MALE','79','0','0','1','0','1','1','Shot by off-duty police (Killed)','Killed','NO'),
('Yoyito Café','6-Jun-10','10:00 PM','Florida','Commerce','Gerardo Regalado','MALE','37','0','0','1','4','3','7','Fled the scene; Committed Suicide','Suicide','NO'),
('Emcore Corporation','12-Jul-10','9:30 AM','New Mexico','Commerce','Robert Reza','MALE','37','0','0','1','2','4','6','Suicide when police arrived','Suicide','NO'),
('Hartford Beer Distribution Center','3-Aug-10','7:00 AM','Connecticut','Commerce','Omar Sheriff Thornton','MALE','34','0','0','2','8','2','10','Suicide when police arrived','Suicide','NO'),
('Kraft Foods Factory','9-Sep-10','8:35 PM','Pennsylvania','Commerce','Yvonne Hiller','FEMALE','43','0','0','1','2','1','3','Surrendered to Police','Arrested','YES'),
('Fort Bliss Convenience Store','20-Sep-10','3:00 PM','Texas','Government','Steven Jay Kropf','MALE','63','0','0','1','1','1','2','Shot by police (Killed)','Killed','NO'),
('AmeriCold Logistics','22-Sep-10','9:54 PM','Nebraska','Commerce','Akouch Kashoual','MALE','26','0','0','1','0','3','3','Suicide before police arrived','Suicide','NO'),
('Gainesville, Florida','4-Oct-10','4:00 PM','Florida','Open Space','Clifford Louis Miller Jr','MALE','24','0','0','1','1','5','6','Suicide before police arrived','Suicide','NO'),
('Kelly Elementary School','8-Oct-10','12:10 PM','California','Education','Brendan O’Rourke (aka Brandon O’Rourke)','MALE','41','0','0','1','0','2','2','Physical intervention by civilian','Arrested','NO'),
('Washington, D.C. Department of Public Works','13-Oct-10','6:14 AM','District of Columbia','Government',null,null,null,'0','0','1','1','1','2','Fled the scene','Escaped (Never Caught)','NO'),
('Walmart','29-Oct-10','8:57 AM','Nevada','Commerce','John Dennis Gillane','MALE','45','0','0','2','0','3','3','Surrendered to Police','Arrested','YES'),
('Panama City School Board Meeting','14-Dec-10','2:14 PM','Florida','Education','Clay Allen Duke','MALE','56','0','0','1','0','0','0','Suicide after engaging police','Suicide','NO'),
('Millard South High School','5-Jan-11','12:44 PM','Nebraska','Education','Richard L. Butler Jr','MALE','17','0','0','1','1','1','2','Fled the scene; Committed Suicide','Suicide','NO'),
('Safeway Grocery','8-Jan-11','10:10 AM','Arizona','Open Space','Jared Lee Loughner','MALE','22','0','0','1','6','13','19','Physical intervention by civilian','Arrested','NO'),
('Minaret Temple 174','8-Apr-11','11:27 PM','Pennsylvania','Commerce','Kanai Daniel Avery','MALE','16','0','0','1','2','8','10','Physical Intervention by security guard','Arrested','NO'),
('Copley Township Neighborhood, Ohio','7-Aug-11','10:55 AM','Ohio','Residence','Michael Edward Hance','MALE','51','0','0','2','7','1','8','Shot by police (Killed)','Killed','NO'),
('House Party in South Jamaica, New York','27-Aug-11','12:40 AM','New York','Residence','Tyrone Miller','MALE','22','0','0','2','0','11','11','Fled the scene','Escaped (Arrested Later)','NO'),
('International House of Pancakes','6-Sep-11','8:58 AM','Nevada','Commerce','Eduardo Sencion (aka Eduardo Perez-Gonzalez)','MALE','32','1','0','0','4','7','11','Suicide before police arrived','Suicide','NO'),
('Crawford County Courthouse','13-Sep-11','3:37 PM','Kansas','Government','Jesse Ray Palmer','MALE','48','1','0','3','0','1','1','Shot by police (Killed)','Killed','NO'),
('Lehigh Southwest Cement Plant','5-Oct-11','4:15 AM','California','Commerce','Frank William Allman (aka Shareef Allman)','MALE','49','2','1','1','3','7','10','Fled the scene; Shot by police (Killed)','Killed','NO'),
('Salon Meritage','12-Oct-11','1:20 PM','California','Commerce','Scott Evans Dekraai','MALE','41','0','0','3','7','1','8','Fled the scene','Escaped (Arrested Later)','NO'),
('Southern California Edison Corporate Office Building','16-Dec-11','1:30 PM','California','Commerce','Andre Turner','MALE','51','0','0','1','2','2','4','Suicide before police arrived','Suicide','NO'),
('McBride Lumber Company','13-Jan-12','6:10 AM','North Carolina','Commerce','Ronald Dean Davis','MALE','50','0','1','0','3','1','4','Fled the scene; Committed Suicide','Suicide','NO'),
('Middletown City Court','8-Feb-12','9:05 AM','New York','Government','Timothy Patrick Mulqueen','MALE','43','0','1','0','0','1','1','Shot by police (Killed)','Killed','NO'),
('Chardon High School','27-Feb-12','7:30 AM','Ohio','Education','Thomas Michael Lane, III','MALE','17','0','0','1','3','3','6','Physical intervention by civilian; fled the scene','Escaped (Arrested Later)','NO'),
('University of Pittsburgh Medical Center, Western Psychiatric Institute and Clinic','8-Mar-12','1:40 PM','Pennsylvania','Education','John Schick','MALE','30','0','0','2','1','7','8','Shot by police (Killed)','Killed','NO'),
('J.T. Tire','23-Mar-12','3:02 PM','North Carolina','Commerce','O’Brian McNeil White','MALE','24','0','0','1','2','2','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Oikos University','2-Apr-12','10:30 AM','California','Education','Su Nam Ko (aka One L. Goh)','MALE','43','0','0','1','7','3','10','Fled the scene','Escaped (Arrested Later)','NO'),
('Streets of Tulsa, Oklahoma','6-Apr-12','1:03 AM','Oklahoma','Open Space','Jacob Carl England & Alvin Lee Watts','MALE & MALE','19 & 32','0','0','2','3','2','5','Fled the scene','Escaped (Arrested Later)','NO'),
('Café Racer','30-May-12','10:52 AM','Washington','Commerce','Ian Lee Stawicki','MALE','40','0','0','2','5','0','5','Fled the scene; Committed Suicide','Suicide','NO'),
('Copper Top Bar','17-Jul-12','12:29 AM','Alabama','Commerce','Nathan Van Wilkins','MALE','44','1','0','0','0','18','18','Fled the scene','Escaped (Arrested Later)','NO'),
('Cinemark Century 16','20-Jul-12','12:30 AM','Colorado','Commerce','James Eagan Holmes','MALE','24','1','1','1','12','58','70','Surrendered to Police','Arrested','YES'),
('Sikh Temple of Wisconsin','5-Aug-12','10:25 AM','Wisconsin','House of Worship','Wade Michael Page','MALE','40','0','0','1','6','4','10','Suicide after engaging police','Suicide','NO'),
('Perry Hall High School','27-Aug-12','10:45 AM','Maryland','Education','Robert Wayne Gladden Jr.','MALE','15','0','1','0','0','1','1','Physical intervention by civilian','Arrested','NO'),
('Pathmark Supermarket','31-Aug-12','4:00 AM','New Jersey','Commerce','Terence Tyler','MALE','23','1','0','1','2','0','2','Suicide before police arrived','Suicide','NO'),
('Accent Signage Systems','27-Sep-12','4:35 PM','Minnesota','Commerce','Andrew John Engeldinger','MALE','36','0','0','1','6','2','8','Suicide before police arrived','Suicide','NO'),
('Las Dominicanas M&M Hair Salon','18-Oct-12','11:04 AM','Florida','Commerce','Bradford Ramon Baumet','MALE','36','0','0','1','3','1','4','Fled the scene; Committed Suicide','Suicide','NO'),
('Azana Day Salon','21-Oct-12','11:09 AM','Wisconsin','Commerce','Radcliffe Franklin Haughton','MALE','45','0','0','1','3','4','7','Suicide before police arrived','Suicide','NO'),
('Valley Protein','6-Nov-12','8:15 AM','California','Commerce','Lawrence Jones','MALE','42','0','0','1','2','2','4','Suicide before police arrived','Suicide','NO'),
('Clackamas Town Center Mall','11-Dec-12','3:25 PM','Oregon','Commerce','Jacob Tyler Roberts','MALE','22','1','0','0','2','1','3','Suicide before police arrived','Suicide','NO'),
('Sandy Hook Elementary School and Residence','14-Dec-12','9:30 AM','Connecticut','Education','Adam Lanza','MALE','20','1','0','2','27','2','29','Suicide when police arrived','Suicide','NO'),
('St. Vincent’s Hospital','15-Dec-12','4:00 AM','Alabama','Health Care','Jason Heath Letts','MALE','38','0','0','1','0','3','3','Shot by police (Killed)','Killed','NO'),
('Frankstown Township, Pennsylvania','21-Dec-12','8:59 AM','Pennsylvania','Open Space','Jeffrey Lee Michael','MALE','44','0','0','2','3','3','6','Shot by police (Killed)','Killed','NO'),
('Taft Union High School','10-Jan-13','8:59 AM','California','Education','Bryan Oliver','MALE','16','0','1','0','0','2','2','Verbal intervention by civilian','Arrested','NO'),
('Osborn Maledon Law Firm','30-Jan-13','10:45 AM','Arizona','Commerce','Arthur Douglas Harmon, III','MALE','70','0','0','1','2','1','3','Fled the scene; Committed Suicide','Suicide','NO'),
('John’s Barbershop and Gaffey’s Clean Car Center','13-Mar-13','9:30 AM','New York','Commerce','Kurt Myers','MALE','64','0','1','0','4','2','6','Fled the scene; Shot by police (Killed)','Killed','NO'),
('New River Community College, Satellite Campus','12-Apr-13','1:55 PM','Virginia','Education','Neil Allen MacInnis','MALE','22','0','1','0','0','2','2','Physical Intervention by security guard','Arrested','NO'),
('Pinewood Village Apartments','21-Apr-13','9:30 PM','Washington','Residence','Dennis Clark III','MALE','27','0','1','1','4','0','4','Shot by police (Killed)','Killed','NO'),
('Brady, Texas and Jacksonville, North Carolina','26-May-13','4:30 AM','Texas','Open Space','Esteban Jimenez Smith','MALE','23','1','0','1','2','5','7','Shot by police (Killed)','Killed','NO'),
('Santa Monica College and Residence','7-Jun-13','11:52 AM','California','Education','John Zawahri','MALE','23','0','0','1','5','4','9','Shot by police (Killed)','Killed','NO'),
('Parking Lots for Kellum Law Firm and Walmart','21-Jun-13','11:44 AM','North Carolina','Open Space','Lakin Anthony Faust','MALE','23','0','1','0','0','4','4','Shot by police (Survived)','Arrested','NO'),
('Hialeah Apartment Building','26-Jul-13','6:30 PM','Florida','Residence','Pedro Alberto Vargas','MALE','42','0','0','1','6','0','6','Shot by police (Killed)','Killed','NO'),
('Pennsylvania Municipal Building','5-Aug-13','7:19 PM','Pennsylvania','Government','Rockne Warren Newell','MALE','59','1','0','1','3','2','5','Physical intervention by civilian','Arrested','NO'),
('Lake Butler, Florida','24-Aug-13','9:20 AM','Florida','Open Space','Hubert Allen Jr.','MALE','72','1','1','0','2','2','4','Fled the scene; Committed Suicide','Suicide','NO'),
('Washington Navy Yard Building 197','16-Sep-13','8:16 AM','Washington','Government','Aaron Alexis','MALE','34','0','1','1','12','7','19','Shot by police (Killed)','Killed','NO'),
('Sparks Middle School','21-Oct-13','7:16 AM','Nevada','Education','Jose Reyes','MALE','12','0','0','1','1','2','3','Suicide before police arrived','Suicide','NO'),
('Albuquerque, New Mexico','26-Oct-13','11:20 AM','New Mexico','Open Space','Christopher Thomas Chase','MALE','35','2','0','3','0','4','4','Shot by police (Killed)','Killed','NO'),
('Los Angeles International Airport','1-Nov-13','9:18 AM','California','Government','Paul Anthony Ciancia','MALE','23','1','0','0','1','3','4','Shot by police (Survived)','Arrested','NO'),
('Arapahoe High School','13-Dec-13','12:30 PM','Colorado','Education','Karl Halverson Pierson','MALE','18','0','1','0','1','0','1','Suicide when police arrived','Suicide','NO'),
('Renown Regional Medical Center','17-Dec-13','2:00 PM','Nevada','Health Care','Alan Oliver Frazier','MALE','51','0','1','2','1','2','3','Suicide when police arrived','Suicide','NO'),
('Berrendo Middle School','14-Jan-14','7:30 AM','New Mexico','Education','Mason Andrew Campbell','MALE','12','0','1','0','0','3','3','Verbal intervention by civilian','Arrested','NO'),
('Martin’s Supermarket','15-Jan-14','10:09 PM','Indiana','Commerce','Shawn Walter Bair','MALE','22','0','0','1','2','0','2','Shot by police (Killed)','Killed','NO'),
('The Mall in Columbia','25-Jan-14','11:15 AM','Maryland','Commerce','Darion Marcus Aguilar','MALE','19','0','1','0','2','5','7','Suicide before police arrived','Suicide','NO'),
('Cedarville Rancheria Tribal Office','20-Feb-14','3:30 PM','California','Government','Cherie Louise Rhoades','FEMALE','44','0','0','1','4','2','6','Physical intervention by civilian','Arrested','NO'),
('Fort Hood Army Base','2-Apr-14','4:00 PM','Texas','Government','Ivan Antonio Lopez-Lopez','MALE','34','0','0','1','3','12','15','Suicide when police arrived','Suicide','NO'),
('Jewish Community Center of Greater Kansas City and Village Shalom Retirement Community','13-Apr-14','1:00 PM','Kansas','House of Worship','Frazier Glenn Miller, Jr.','MALE','73','0','1','2','3','0','3','Fled the scene','Escaped (Arrested Later)','NO'),
('Federal Express','29-Apr-14','5:50 AM','Georgia','Commerce','Geddy Lee Kramer','MALE','19','0','1','0','0','6','6','Suicide before police arrived','Suicide','NO'),
('Residence and Construction Site in Jonesboro, Arkansas','3-May-14','1:00 PM','Arkansas','Residence','Porfirio Sayago-Hernandez','MALE','40','0','0','1','3','4','7','Fled the scene; Committed Suicide','Suicide','NO'),
('Multiple Locations in Isla Vista, California','23-May-14','9:27 PM','California','Open Space','Elliot Rodger','MALE','22','0','0','1','6','14','20','Suicide after engaging police','Suicide','NO'),
('Seattle Pacific University','5-Jun-14','3:25 PM','Washington','Education','Aaron Rey Ybarra','MALE','26','0','1','0','1','3','4','Physical intervention by civilian','Arrested','NO'),
('Forsyth County Courthouse','6-Jun-14','10:00 AM','Georgia','Government','Dennis Ronald Marx','MALE','48','1','0','3','0','1','1','Shot by police (Killed)','Killed','NO'),
('Cici’s Pizza and Walmart','8-Jun-14','11:20 AM','Nevada','Commerce','Jerad Dwain Miller & Amanda Renee Miller (Husband & Wife)','MALE & FEMALE','31 & 22','0','1','2','3','0','3','Shot by police (Killed); Suicide after engaging police','Killed & Suicide','NO'),
('Reynolds High School','10-Jun-14','8:05 AM','Oregon','Education','Jared Michael Padgett','MALE','15','1','0','1','1','1','2','Suicide when police arrived','Suicide','NO'),
('Sister Marie Lenahan Wellness Center','24-Jul-14','2:20 PM','Pennsylvania','Health Care','Richard Steven Plotts','MALE','49','0','0','1','1','1','2','Shot by civilian (Survived)','Arrested','NO'),
('Hon-Dah Resort Casino and Conference Center','2-Aug-14','6:38 PM','Arizona','Commerce','Justin Joe Armstrong','MALE','28','1','0','0','0','2','2','Shot by police (Killed)','Killed','NO'),
('United Parcel Service','23-Sep-14','9:20 AM','Alabama','Commerce','Kerry Joe Tesney','MALE','45','0','0','1','2','0','2','Suicide before police arrived','Suicide','NO'),
('Marysville-Pilchuck High School','24-Oct-14','10:39 AM','Washington','Education','Jaylen Ray Fryberg','MALE','15','0','0','1','4','3','7','Verbal intervention by civilian; Suicide before police arrived','Suicide','NO'),
('Florida State University','20-Nov-14','12:00 AM','Florida','Education','Myron May','MALE','31','0','0','1','0','3','3','Shot by police (Killed)','Killed','NO'),
('Neighborhood in Tallahassee, Florida','22-Nov-14','10:15 AM','Florida','Residence','Curtis Wade Holley','MALE','53','0','0','1','1','1','2','Shot by off-duty police (Killed)','Killed','NO'),
('Government Buildings in Austin, Texas','28-Nov-14','2:21 AM','Texas','Government','Larry Steven McQuilliams','MALE','49','1','0','1','0','0','0','Shot by police (Killed)','Killed','NO'),
('Multiple Locations in Moscow, Idaho','10-Jan-15','2:31 PM','Idaho','Open Space','John Lee (aka Kane Grzebielski)','MALE','29',null,null,null,'3','1','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Melbourne Square Mall','17-Jan-15','9:31 AM','Florida','Commerce','Jose Garcia-Rodriguez','MALE','57','0','0','3','1','1','2','Suicide before police arrived','Suicide','NO'),
('New Hope City Hall','26-Jan-15','7:15 PM','Minnesota','Government','Raymond Kenneth Kmetz','MALE','68','0','1','0','0','4','4','Shot by police (Killed)','Killed','NO'),
('Monroeville Mall','7-Feb-15','7:33 PM','Pennsylvania','Commerce','Tarod Tyrell Thornhill','MALE','17','0','0','1','0','3','3','Fled the scene','Escaped (Arrested Later)','NO'),
('Sioux Steel Pro∙Tec','12-Feb-15','2:00 PM','South Dakota','Commerce','Jeffrey Scott DeZeeuw','MALE','51','0','0','1','1','2','3','Fled the scene; Committed Suicide','Suicide','NO'),
('Dad’s Sing Along Club','14-Mar-15','2:00 AM','Texas','Commerce','Richard Castilleja','MALE','29','0','0','1','0','2','2','Shot by police (Killed)','Killed','NO'),
('Multiple Locations in Mesa, Arizona','18-Mar-15','8:39 AM','Arizona','Open Space','Ryan Elliot Giroux','MALE','41','0','0','1','1','5','6','Fled the scene','Escaped (Arrested Later)','NO'),
('Residence in Panama City Beach, Florida','28-Mar-15','12:53 AM','Florida','Residence','David Jamichael Daniels','MALE','21','0','0','1','0','7','7','Fled the scene','Escaped (Arrested Later)','NO'),
('North Milwaukee Avenue, Chicago','19-Apr-15','11:50 PM','Illinois','Open Space','Everardo Custodio','MALE','21','0','0','1','0','0','0','Shot by civilian','Arrested','NO'),
('Trestle Trail Bridge, Wisconsin','3-May-15','7:30 PM','Wisconsin','Open Space','Sergio Daniel Valencia Del Toro','MALE','27','0','0','2','3','1','4','Suicide before police arrived','Suicide','NO'),
('Walmart Supercenter','26-May-15','1:00 AM','North Dakota','Commerce','Marcell Travon Willis','MALE','21','0','0','1','1','1','2','Suicide before police arrived','Suicide','NO'),
('Emanuel African Methodist Episcopal Church','17-Jun-15','9:00 PM','South Carolina','House of Worship','Dylann Storm Roof','MALE','21','1','0','0','9','0','9','Fled the scene','Escaped (Arrested Later)','NO'),
('Omni Austin Hotel Downtown','5-Jul-15','4:48 AM','Texas','Commerce','Michael Holt','MALE','35','1','0','0','1','0','1','Shot by police (Killed)','Killed','NO'),
('Two Military Centers in Chattanooga, Tennessee','16-Jul-15','10:51 AM','Tennessee','Government','Mohammad Youssuf Abdulazeez','MALE','24','1','0','0','5','2','7','Shot by police (Killed)','Killed','NO'),
('Grand 16 Theatre','23-Jul-15','7:15 PM','Louisiana','Commerce','John Russell Houser','MALE','59','0','0','1','2','9','11','Suicide when police arrived','Suicide','NO'),
('Umpqua Community College','1-Oct-15','10:38 AM','Oregon','Education','Christopher Sean Harper-Mercer','MALE','26','1','0','3','9','7','16','Suicide after engaging police','Suicide','NO'),
('Syverud Law Office and Miller-Meier Limb and Brace, Inc.','26-Oct-15','1:56 PM','Iowa','Commerce','Robert Lee Mayes, Jr.','MALE','40','0','0','1','0','2','2','Suicide when police arrived','Suicide','NO'),
('Neighborhood in Colorado Springs, Colorado','31-Oct-15','8:55 AM','Colorado','Open Space','Noah Jacob Harpham','MALE','33','1','0','2','3','0','3','Shot by police (Killed)','Killed','NO'),
('Planned Parenthood – Colorado Springs Westside Health Center','27-Nov-15','11:38 AM','Colorado','Health Care','Robert Lewis Dear, Jr.','MALE','57','1','0','0','3','9','12','Surrendered to Police','Arrested','YES'),
('Inland Regional Center','2-Dec-15','11:30 AM','California','Commerce','Syed Rizwan Farook & Tashfeen Malik (Husband & Wife)','MALE & FEMALE','28 & 29','2','0','2','14','22','36','Fled the scene; Shot by police (Killed)','Killed','NO'),
('Multiple Locations in Kalamazoo, Michigan','20-Feb-16','5:40 PM','Michigan','Open Space','Jason Brian Dalton','MALE','45','0','0','1','6','2','8','Fled the scene','Escaped (Arrested Later)','NO'),
('Excel Industries and Newton and Hesston, Kansas','25-Feb-16','4:57 PM','Kansas','Commerce','Cedric Larry Ford','MALE','38','1','0','1','3','14','17','Shot by police (Killed)','Killed','NO'),
('Madison Junior/Senior High School','29-Feb-16','11:30 AM','Ohio','Education','James Austin Hancock','MALE','14','0','0','1','0','4','4','Surrendered to Police','Arrested','YES'),
('Prince George’s County Police Department District 3 Station','13-Mar-16','4:30 PM','Maryland','Government','Michael Ford','MALE','22','0','0','1','1','0','1','Shot by the police (Survived)','Arrested','NO'),
('Antigo High School','23-Apr-16','11:02 PM','Wisconsin','Education','Jakob Edward Wagner','MALE','18','1','0','0','0','2','2','Shot by police (Killed)','Killed','NO'),
('Knight Transportation Building','4-May-16','8:45 AM','Texas','Commerce','Marion Guy Williams','MALE','65','0','1','1','1','2','3','Suicide when police arrived','Suicide','NO'),
('Arizona State Route 87','24-May-16','8:30 PM','Arizona','Open Space','James David Walker','MALE','36','1','0','0','0','2','2','Fled the scene','Escaped (Arrested Later)','NO'),
('Memorial Tire and Auto','29-May-16','10:15 AM','Texas','Commerce','Dionisio Agustine Garza III','MALE','25','1','0','1','1','6','7','Shot at by Civilian (Missed); Shot by police (Killed)','Killed','NO'),
('Pulse Nightclub','12-Jun-16','2:02 AM','Florida','Commerce','Omar Mir Seddique Mateen','MALE','29','1','0','1','49','53','102','Shot by police (Killed)','Killed','NO'),
('Days Inn and Volunteer Parkway','7-Jul-16','2:18 AM','Tennessee','Open Space','Lakeem Keon Scott','MALE','37','1','0','1','1','3','4','Shot by police (Survived)','Arrested','NO'),
('Protest in Dallas, Texas','7-Jul-16','9:00 PM','Texas','Open Space','Micah Xavier Johnson','MALE','25','2','0','1','5','11','16','Killed by police controlled bomb carying robot','Killed','NO'),
('Benny’s Car Wash, Oil Change & B-Quik and Hair Crown Beauty Supply','17-Jul-16','8:40 AM','Louisiana','Open Space','Gavin Eugene Long','MALE','29','2','0','1','3','3','6','Shot by police (Killed)','Killed','NO'),
('House Party in Mukilteo, Washington','30-Jul-16','12:07 AM','Washington','Residence','Allen Christopher Ivanov','MALE','19','1','0','0','3','1','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Multiple Locations in Joplin, Missouri','13-Aug-16','5:08 AM','Missouri','Open Space','Tom Stanley Mourning II','MALE','26','1','0','1','0','5','5','Unclear','Arrested','Unclear'),
('Multiple Locations in Philadelphia, Pennsylvania','16-Sep-16','11:15 PM','Pennsylvania','Open Space','Nicholas N. Glenn','MALE','25','0','0','1','1','5','6','Shot by police (Killed)','Killed','NO'),
('Cascade Mall','23-Sep-16','6:52 PM','Washington','Commerce','Arcan Cetin','MALE','20','1','0','0','5','0','5','Fled the scene','Escaped (Arrested Later)','NO'),
('Law Street in Houston, Texas','26-Sep-16','6:30 AM','Texas','Open Space','Nathan Desai','MALE','46','0','0','1','0','9','9','Shot by police (Killed)','Killed','NO'),
('Townville Elementary School','28-Sep-16','1:45 PM','South Carolina','Education','Jesse Dewitt Osborne','MALE','14','0','0','1','2','3','5','Armed intervention by civilian (no shots fired)','Arrested','NO'),
('FreightCar America','25-Oct-16','6:00 AM','Virginia','Commerce','Getachew Tereda Fekede','MALE','53','0','0','1','1','3','4','Suicide before police arrived','Suicide','NO'),
('H-E-B Grocery Store','28-Nov-16','3:15 AM','Texas','Commerce','Raul Lopez Saenz','MALE','25','0','0','1','1','3','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Fort Lauderdale-Hollywood International Airport','6-Jan-17','1:15 PM','Florida','Government','Esteban Santiago-Ruiz','MALE','26','0','0','1','5','8','13','Surrendered to Police','Arrested','YES'),
('West Liberty-Salem High School','20-Jan-17','7:36 AM','Ohio','Education','Ely Ray Serna','MALE','17','0','1','0','0','2','2','Physical intervention by civilian','Arrested','NO'),
('Marathon Savings Bank and Tlusty, Kennedy & Dirks, S.C.','22-Mar-17','12:27 PM','Wisconsin','Commerce','Nengmy Vang','MALE','45','1','0','1','4','0','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Las Vegas Bus','25-Mar-17','10:45 AM','Nevada','Other','Rolando Bueno Cardenas','MALE','55','0','0','1','1','1','2','Surrendered to Police','Arrested','YES'),
('Residence and Bus Stop in Sanford, Florida','27-Mar-17','6:20 AM','Florida','Open Space','Allen Dion Cashe','MALE','31','1','0','0','2','4','6','Fled the scene','Escaped (Arrested Later)','NO'),
('The Cooler','15-Apr-17','9:30 PM','Illinois','Commerce','Seth Thomas Wallace','MALE','32','0','0','1','0','4','4','Fled the scene','Escaped (Arrested Later)','NO'),
('Multiple Locations in Fresno, California','18-Apr-17','10:45 AM','California','Open Space','Kori Ali Muhammad','MALE','39','0','0','1','3','0','3','Fled the scene','Escaped (Arrested Later)','NO'),
('Group Home in Topeka, Kansas','30-Apr-17','3:50 PM','Kansas','Health Care','Joshua James Ray Gueary','MALE','25','0','0','1','3','1','4','Suicide before police arrived','Suicide','NO'),
('La Jolla Crossroads Apartment Complex','30-Apr-17','6:00 PM','California','Residence','Peter Raymond Selis','MALE','49','0','0','1','1','7','8','Shot by police (Killed)','Killed','NO'),
('Pine Kirk Care Center','12-May-17','7:30 AM','Ohio','Health Care','Thomas Harry Hartless','MALE','43','0','1','1','3','0','3','Suicide before police arrived','Suicide','NO'),
('Fiamma Inc.','5-Jun-17','8:00 AM','Florida','Commerce','John Robert Neumann Jr','MALE','45','0','0','1','5','0','5','Suicide before police arrived','Suicide','NO'),
('Weis Supermarket','8-Jun-17','1:00 AM','Pennsylvania','Commerce','Randy Robert Stair','MALE','24','0','2','0','3','0','3','Suicide before police arrived','Suicide','NO'),
('Eugene Simpson Stadium Park','14-Jun-17','7:15 AM','Virginia','Open Space','James Thomas Hodgkinson','MALE','66','1','0','1','0','4','4','Shot by police (Killed)','Killed','NO'),
('UPS Customer Center','14-Jun-17','8:55 AM','California','Commerce','Jimmy Chanh Lam','MALE','38','0','0','2','3','5','8','Suicide when police arrived','Suicide','NO'),
('Bronx-Lebanon Hospital Center','30-Jun-17','2:50 PM','New York','Health Care','Dr. Henry Michael Bello','MALE','45','1','0','0','1','6','7','Suicide before police arrived','Suicide','NO'),
('Highway 141 in Gateway, Colorado','30-Jul-17','4:15 PM','Colorado','Open Space','Rick Whited','MALE','54','0','0','1','0','0','0','Fled the scene after engaging security guards','Escaped (Arrested Later)','NO'),
('Clovis-Carver Public Library','28-Aug-17','4:15 PM','New Mexico','Government','Nathaniel Ray Jouett','MALE','16','0','0','1','2','4','6','Surrendered to Police','Arrested','YES'),
('Freeman High School','13-Sep-17','10:00 AM','Washington','Education','Caleb Sharpe','MALE','15','1','0','1','1','3','4','Verbal & Physical intervention by civilian','Arrested','YES'),
('Burnette Chapel Church of Christ','24-Sep-17','11:15 AM','Tennessee','House of Worship','Emanuel Kidega Samson','MALE','25','0','0','2','1','7','8','Armed intervention by civilian (no shots fired)','Arrested','NO'),
('Route 91 Harvest Festival','1-Oct-17','10:08 PM','Nevada','Open Space','Stephen Craig Paddock','MALE','64','4','0','0','58','489','547','Suicide before police arrived','Suicide','NO'),
('Advanced Granite Solutions and 28th Street Auto Sales and Service','18-Oct-17','8:58 AM','Maryland','Commerce','Radee Labeeb Prince','MALE','37','0','0','1','3','3','6','Fled the scene','Escaped (Arrested Later)','NO'),
('Multiple Locations in Clearlake Oaks, California','23-Oct-17','11:23 AM','California','Commerce','Alan Ashmore','MALE','61','0','1','1','2','3','5','Shot at by Civilian (Missed); Fled the scene','Escaped (Arrested Later)','NO'),
('Walmart in Thornton, Colorado','1-Nov-17','6:10 PM','Colorado','Commerce','Scott Allen Ostrem','MALE','47','0','0','1','3','0','3','Fled the scene','Escaped (Arrested Later)','NO'),
('First Baptist Church in Sutherland Springs, Texas','5-Nov-17','11:20 AM','Texas','House of Worship','Devin Patrick Kelley','MALE','26','1','0','0','26','20','46','Shot by civilan (survived); committed suicide before police arrived','Suicide','NO'),
('Rancho Tehama Elementary School and Multiple Locations in Tehama County, California','14-Nov-17','7:53 AM','California','Education','Kevin Janson Neal','MALE','44','1','0','2','5','14','19','Suicide after engaging police','Suicide','NO'),
('Dollar General Store','14-Nov-17','2:45 PM','New York','Commerce','Travis Green','MALE','29','2','0','0','0','1','1','Civilian intervention with automobile; Physical intervention by police','Arrested','NO'),
('Schlenker Automotive','17-Nov-17','4:30 PM','Florida','Commerce','Robert Lorenzo Bailey, Jr','MALE','28','0','0','1','1','1','2','Shot by civilian (Survived)','Arrested','NO'),
('Aztec High School','7-Dec-17','8:00 AM','New Mexico','Education','William Edward Atchison','MALE','21','0','0','1','2','0','2','Suicide before police arrived','Suicide','NO'),
('Multiple Locations in Baltimore, Maryland','15-Dec-17','2:55 PM','Maryland','Open Space','Mausean Vittorio Quran Carter','MALE','30','1','0','1','0','3','3','Physical intervention by civilian','Arrested','NO'),
('University of Cincinnati Medical Center','20-Dec-17','2:00 PM','Ohio','Health Care','Isaiah Currie','MALE','20','0','0','2','0','1','1','Suicide when police arrived','Suicide','NO'),
('Marshall County High School','23-Jan-18','7:57 AM','Kentucky','Education','Gabriel Ross Parker','MALE','15','0','0','1','2','21','23','Surrendered to Police','Arrested','YES'),
('Marjory Stoneman Douglas High School','14-Feb-18','2:30 PM','Florida','Education','Nikolas Jacob Cruz','MALE','19','1','0','0','17','17','34','Fled the scene','Escaped (Arrested Later)','NO'),
('City Grill Café','7-Mar-18','6:30 AM','Alabama','Commerce','Walter Frank Thomas','MALE','64','1','0','0','2','2','4','Fled the scene','Escaped (Arrested Later)','NO'),
('YouTube Headquarters','3-Apr-18','12:45 PM','California','Commerce','Nasim Najafi Aghdam','FEMALE','39','0','0','1','0','4','4','Suicide before police arrived','Suicide','NO'),
('Waffle House','22-Apr-18','3:30 AM','Tennessee','Commerce','Travis Jeffrey Reinking','MALE','29','1','0','0','4','4','8','Physical intervention by civilian; fled the scene','Escaped (Arrested Later)','NO'),
('Highway 365 Near Whitehall Road in Gainesville, Georgia','4-May-18','11:58 AM','Georgia','Open Space','Rex Whitmire Harbour','MALE','26','0','0','1','0','3','3','Suicide when police arrived','Suicide','NO'),
('Dixon High School','16-May-18','8:00 AM','Illinois','Education','Matthew A. Milby Jr.','MALE','19','1','0','0','0','0','0','Shot by police (Survived)','Arrested','NO'),
('Santa Fe High School','18-May-18','7:30 AM','Texas','Education','Dimitrios Pagourtzis','MALE','17','0','1','1','10','12','22','Surrendered to Police','Arrested','NO'),
('Louie’s Lakeside Eatery','24-May-18','6:30 PM','Oklahoma','Commerce','Alexander C. Tilghman','MALE','28','0','0','1','0','4','4','Shot by civilian (Killed)','Killed','NO'),
('Noblesville West Middle School','25-May-18','9:06 AM','Indiana','Education',null,'MALE','13','0','0','2','0','2','2','Physical intervention by civilian','Arrested','NO'),
('Highway 509 Near Seattle-Tacoma International Airport','13-Jun-18','1:42 PM','Washington','Open Space',null,null,null,null,null,null,'0','0','0','Fled the scene','Escaped (Never Caught)','NO'),
('Capital Gazette','29-Jun-18','2:34 PM','Maryland','Commerce','Jarrod Warren Ramos','MALE','38','0','1','0','5','2','7','Surrendered to Police','Arrested','YES'),
('Ben E. Keith Gulf Coast','20-Aug-18','2:00 AM','Texas','Commerce','Kristine Peralez','FEMALE','38','0','0','1','1','1','2','Suicide when police arrived','Suicide','NO'),
('GLHF Game Bar','26-Aug-18','1:34 PM','Florida','Commerce','David Bennett Katz','MALE','24','0','0','2','2','11','13','Suicide before police arrived','Suicide','NO'),
('Fifth Third Center','6-Sep-18','9:10 AM','Ohio','Commerce','Omar Enrique Santa Perez','MALE','29','0','0','1','3','2','5','Shot by police (Killed)','Killed','NO'),
('T & T Trucking, Inc. and a Residence','12-Sep-18','5:20 PM','California','Commerce','Javier Casarez','MALE','54','0','0','1','5','0','5','Fled the scene; Suicide when police arrived','Suicide','NO'),
('WTS Paradigm','19-Sep-18','10:30 AM','Wisconsin','Commerce','Anthony Yente Tong','MALE','43','0','0','1','0','4','4','Shot by police (Killed)','Killed','NO'),
('Masontown Borough Municipal Center','19-Sep-18','2:00 PM','Pennsylvania','Government','Patrick Shaun Dowdell','MALE','61','0','0','1','0','4','4','Shot by police (Killed)','Killed','NO'),
('Rite Aid Perryman Distribution Center’s Liberty Support Center','20-Sep-18','9:06 AM','Maryland','Commerce','Snochia Moseley','FEMALE','26','0','0','1','3','3','6','Suicide before police arrived','Suicide','NO'),
('Kroger Grocery Store in Jeffersontown, Kentucky','24-Oct-18','3:00 PM','Kentucky','Commerce','Gregory Alan Bush','MALE','51','0','0','1','2','0','2','Shot at by civilian (missed); Fled the scene','Escaped (Arrested Later)','NO'),
('Tree of Life Synagogue','27-Oct-18','9:45 AM','Pennsylvania','House of Worship','Robert Gregory Bowers','MALE','46','1','0','3','11','6','17','Shot by police (Survived)','Arrested','NO'),
('Hot Yoga Tallahassee','2-Nov-18','5:37 PM','Florida','Commerce','Scott Paul Beierle','MALE','40','0','0','1','2','5','7','Suicide before police arrived','Suicide','NO'),
('Helen Vine Recovery Center','5-Nov-18','1:30 AM','California','Health Care','Davance Lamar Reed','MALE','37','0','0','1','1','2','3','Fled the scene','Escaped (Arrested Later)','NO'),
('Borderline Bar and Grill','7-Nov-18','11:20 PM','California','Commerce','Ian David Long','MALE','28','0','0','1','12','16','28','Suicide after engaging police','Suicide','NO'),
('Ben E. Keith Albuquerque','12-Nov-18','6:56 PM','New Mexico','Commerce','Waid Anthony Melton','MALE','30','0','0','1','0','3','3','Fled the scene; Committed Suicide','Suicide','NO'),
('Mercy Hospital & Medical Center','19-Nov-18','3:20 PM','Illinois','Health Care','Juan Lopez','MALE','32','0','0','1','3','0','3','Suicide after engaging police','Suicide','NO'),
('Motel 6 in Albuquerque, New Mexico','24-Dec-18','11:00 AM','New Mexico','Commerce','Abdias Ucdiel Flores-Corado','MALE','35','1','0','0','0','0','0','Shot by police (Killed)','Killed','NO');
